<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="新文件夹\**" />
    <EmbeddedResource Remove="新文件夹\**" />
    <None Remove="新文件夹\**" />
    <Page Remove="新文件夹\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\Interfaces\" />
    <Folder Include="Protos\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dirkster.AvalonDock" Version="4.73.0" />
    <PackageReference Include="Dirkster.AvalonDock.Themes.VS2013" Version="4.73.0" />
    <PackageReference Include="Google.Protobuf" Version="3.25.0" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.60.0" />
    <PackageReference Include="Grpc.Core" Version="2.46.6" />
    <PackageReference Include="Grpc.Net.Client" Version="2.60.0" />
    <PackageReference Include="Grpc.Tools" Version="2.60.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

	<ItemGroup>
		<!-- 引入 proto 文件 -->
		<Protobuf Include="Protos\calculator.proto" GrpcServices="Both" />
		<Protobuf Include="Protos\analyzer.proto" GrpcServices="Client" />
	</ItemGroup>

</Project>
